Fix dependency conflict
```(venv) root@DESKTOP-Q78G1EM:/home/test/todowoo# pip install -r requirements.txt
Collecting asgiref==3.4.1 (from -r requirements.txt (line 1))
  Downloading asgiref-3.4.1-py3-none-any.whl.metadata (9.2 kB)
Collecting Django==4.2 (from -r requirements.txt (line 2))
  Downloading Django-4.2-py3-none-any.whl.metadata (4.1 kB)
Collecting gunicorn==20.1.0 (from -r requirements.txt (line 3))
  Downloading gunicorn-20.1.0-py3-none-any.whl.metadata (3.8 kB)
Collecting pytz==2021.1 (from -r requirements.txt (line 4))
  Downloading pytz-2021.1-py2.py3-none-any.whl.metadata (21 kB)
Collecting sqlparse==0.4.1 (from -r requirements.txt (line 5))
  Downloading sqlparse-0.4.1-py3-none-any.whl.metadata (3.4 kB)
Collecting whitenoise==5.3.0 (from -r requirements.txt (line 6))
  Downloading whitenoise-5.3.0-py2.py3-none-any.whl.metadata (3.3 kB)
INFO: pip is looking at multiple versions of django to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install -r requirements.txt (line 2) and asgiref==3.4.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested asgiref==3.4.1
    django 4.2 depends on asgiref<4 and >=3.6.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict```